version: '3.3'
services:
  zuul-gateway:
    image: pkjacob/zuul-gateway:0.0.1-SNAPSHOT
    networks:
      - currency-network
    ports: 
      - "8766:8765"
    depends_on: 
      - eureka-server  
  eureka-server:
    image: pkjacob/eureka-server:0.0.1-SNAPSHOT
    networks:
      - currency-network
    ports: 
      - "8761:8761"
  currency-exchange:
    image: pkjacob/currency-exchange:0.0.1-SNAPSHOT
    networks:
      - currency-network
    depends_on: 
      - mongodb
      - eureka-server
      - zuul-gateway
    #ports: 
    #  - "8080:8080"
  currency-conversion:
    ports:
      - "8081:8081"
    depends_on:
      - currency-exchange
      - eureka-server
    image: pkjacob/currency-conversion:0.0.1-SNAPSHOT
    networks:
      - currency-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - currency-network
    volumes: 
      - db-data:/data/db    
networks:
  currency-network:
volumes: 
  db-data: